package net.hyper.chiseled.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootSubProvider;
import net.hyper.chiseled.registry.ChiseledBlocks;
import net.minecraft.core.HolderLookup;
import java.util.concurrent.CompletableFuture;

public class ChiseledBlockLootTableGen extends FabricBlockLootSubProvider {
    public ChiseledBlockLootTableGen(FabricPackOutput dataOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        dropSelf(ChiseledBlocks.STONE_WALL);
        dropSelf(ChiseledBlocks.POLISHED_STONE);
        dropSelf(ChiseledBlocks.POLISHED_STONE_STAIRS);
        add(ChiseledBlocks.POLISHED_STONE_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_STONE_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_STONE_WALL);
        dropSelf(ChiseledBlocks.SMOOTH_STONE_STAIRS);
        dropSelf(ChiseledBlocks.CUT_STONE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_CUT_STONE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_STONE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_STONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_STONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.MOSSY_CUT_STONE_BRICKS);
        dropSelf(ChiseledBlocks.MOSSY_CUT_STONE_BRICK_STAIRS);
        add(ChiseledBlocks.MOSSY_CUT_STONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.MOSSY_CUT_STONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.STONE_TILES);
        dropSelf(ChiseledBlocks.CRACKED_STONE_TILES);
        dropSelf(ChiseledBlocks.STONE_TILE_STAIRS);
        add(ChiseledBlocks.STONE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.STONE_TILE_SLAB));
        dropSelf(ChiseledBlocks.STONE_TILE_WALL);
        dropSelf(ChiseledBlocks.MOSSY_STONE_TILES);
        dropSelf(ChiseledBlocks.MOSSY_STONE_TILE_STAIRS);
        add(ChiseledBlocks.MOSSY_STONE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.MOSSY_STONE_TILE_SLAB));
        dropSelf(ChiseledBlocks.MOSSY_STONE_TILE_WALL);

        dropSelf(ChiseledBlocks.POLISHED_GRANITE_WALL);
        dropSelf(ChiseledBlocks.POLISHED_GRANITE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_POLISHED_GRANITE_BRICKS);
        dropSelf(ChiseledBlocks.POLISHED_GRANITE_BRICK_STAIRS);
        add(ChiseledBlocks.POLISHED_GRANITE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_GRANITE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_GRANITE_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_CUT_POLISHED_GRANITE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_GRANITE_TILES);
        dropSelf(ChiseledBlocks.CRACKED_POLISHED_GRANITE_TILES);
        dropSelf(ChiseledBlocks.POLISHED_GRANITE_TILE_STAIRS);
        add(ChiseledBlocks.POLISHED_GRANITE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_GRANITE_TILE_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_GRANITE_TILE_WALL);

        dropSelf(ChiseledBlocks.POLISHED_DIORITE_WALL);
        dropSelf(ChiseledBlocks.POLISHED_DIORITE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_POLISHED_DIORITE_BRICKS);
        dropSelf(ChiseledBlocks.POLISHED_DIORITE_BRICK_STAIRS);
        add(ChiseledBlocks.POLISHED_DIORITE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_DIORITE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_DIORITE_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_CUT_POLISHED_DIORITE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_DIORITE_TILES);
        dropSelf(ChiseledBlocks.CRACKED_POLISHED_DIORITE_TILES);
        dropSelf(ChiseledBlocks.POLISHED_DIORITE_TILE_STAIRS);
        add(ChiseledBlocks.POLISHED_DIORITE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_DIORITE_TILE_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_DIORITE_TILE_WALL);

        dropSelf(ChiseledBlocks.POLISHED_ANDESITE_WALL);
        dropSelf(ChiseledBlocks.POLISHED_ANDESITE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_BRICKS);
        dropSelf(ChiseledBlocks.POLISHED_ANDESITE_BRICK_STAIRS);
        add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_ANDESITE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_ANDESITE_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_CUT_POLISHED_ANDESITE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_ANDESITE_TILES);
        dropSelf(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_TILES);
        dropSelf(ChiseledBlocks.POLISHED_ANDESITE_TILE_STAIRS);
        add(ChiseledBlocks.POLISHED_ANDESITE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_ANDESITE_TILE_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_ANDESITE_TILE_WALL);

        dropSelf(ChiseledBlocks.CUT_DEEPSLATE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_CUT_DEEPSLATE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_DEEPSLATE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_DEEPSLATE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_DEEPSLATE_BRICK_SLAB));

        dropSelf(ChiseledBlocks.CALCITE_STAIRS);
        add(ChiseledBlocks.CALCITE_SLAB, createSlabItemTable(ChiseledBlocks.CALCITE_SLAB));
        dropSelf(ChiseledBlocks.CALCITE_WALL);
        dropSelf(ChiseledBlocks.POLISHED_CALCITE);
        dropSelf(ChiseledBlocks.POLISHED_CALCITE_STAIRS);
        add(ChiseledBlocks.POLISHED_CALCITE_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_CALCITE_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_CALCITE_WALL);
        dropSelf(ChiseledBlocks.CALCITE_BRICKS);
        dropSelf(ChiseledBlocks.CALCITE_BRICK_STAIRS);
        add(ChiseledBlocks.CALCITE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CALCITE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.CALCITE_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_CALCITE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_CALCITE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_CALCITE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_CALCITE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.CALCITE_TILES);
        dropSelf(ChiseledBlocks.CALCITE_TILE_STAIRS);
        add(ChiseledBlocks.CALCITE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.CALCITE_TILE_SLAB));
        dropSelf(ChiseledBlocks.CALCITE_TILE_WALL);

        dropSelf(ChiseledBlocks.DRIPSTONE_STAIRS);
        add(ChiseledBlocks.DRIPSTONE_SLAB, createSlabItemTable(ChiseledBlocks.DRIPSTONE_SLAB));
        dropSelf(ChiseledBlocks.DRIPSTONE_WALL);
        dropSelf(ChiseledBlocks.POLISHED_DRIPSTONE);
        dropSelf(ChiseledBlocks.POLISHED_DRIPSTONE_STAIRS);
        add(ChiseledBlocks.POLISHED_DRIPSTONE_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_DRIPSTONE_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_DRIPSTONE_WALL);
        dropSelf(ChiseledBlocks.DRIPSTONE_BRICKS);
        dropSelf(ChiseledBlocks.DRIPSTONE_BRICK_STAIRS);
        add(ChiseledBlocks.DRIPSTONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.DRIPSTONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.DRIPSTONE_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_DRIPSTONE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_DRIPSTONE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_DRIPSTONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_DRIPSTONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.DRIPSTONE_TILES);
        dropSelf(ChiseledBlocks.DRIPSTONE_TILE_STAIRS);
        add(ChiseledBlocks.DRIPSTONE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.DRIPSTONE_TILE_SLAB));
        dropSelf(ChiseledBlocks.DRIPSTONE_TILE_WALL);

        dropSelf(ChiseledBlocks.MIXED_BRICKS);
        dropSelf(ChiseledBlocks.MIXED_BRICK_STAIRS);
        add(ChiseledBlocks.MIXED_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.MIXED_BRICK_SLAB));
        dropSelf(ChiseledBlocks.MIXED_BRICK_WALL);
        dropSelf(ChiseledBlocks.MOSSY_BRICKS);
        dropSelf(ChiseledBlocks.MOSSY_BRICK_STAIRS);
        add(ChiseledBlocks.MOSSY_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.MOSSY_BRICK_SLAB));
        dropSelf(ChiseledBlocks.MOSSY_BRICK_WALL);

        dropSelf(ChiseledBlocks.PACKED_MUD_STAIRS);
        add(ChiseledBlocks.PACKED_MUD_SLAB, createSlabItemTable(ChiseledBlocks.PACKED_MUD_SLAB));
        dropSelf(ChiseledBlocks.PACKED_MUD_WALL);
        dropSelf(ChiseledBlocks.POLISHED_MUD);
        dropSelf(ChiseledBlocks.POLISHED_MUD_STAIRS);
        add(ChiseledBlocks.POLISHED_MUD_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_MUD_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_MUD_WALL);
        dropSelf(ChiseledBlocks.MOSSY_MUD_BRICKS);
        dropSelf(ChiseledBlocks.MOSSY_MUD_BRICK_STAIRS);
        add(ChiseledBlocks.MOSSY_MUD_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.MOSSY_MUD_BRICK_SLAB));
        dropSelf(ChiseledBlocks.MOSSY_MUD_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_MUD_BRICKS);
        dropSelf(ChiseledBlocks.CUT_MUD_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_MUD_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_MUD_BRICK_SLAB));
        dropSelf(ChiseledBlocks.MOSSY_CUT_MUD_BRICKS);
        dropSelf(ChiseledBlocks.MOSSY_CUT_MUD_BRICK_STAIRS);
        add(ChiseledBlocks.MOSSY_CUT_MUD_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.MOSSY_CUT_MUD_BRICK_SLAB));
        dropSelf(ChiseledBlocks.MUD_TILES);
        dropSelf(ChiseledBlocks.MUD_TILE_STAIRS);
        add(ChiseledBlocks.MUD_TILE_SLAB, createSlabItemTable(ChiseledBlocks.MUD_TILE_SLAB));
        dropSelf(ChiseledBlocks.MUD_TILE_WALL);
        dropSelf(ChiseledBlocks.MOSSY_MUD_TILES);
        dropSelf(ChiseledBlocks.MOSSY_MUD_TILE_STAIRS);
        add(ChiseledBlocks.MOSSY_MUD_TILE_SLAB, createSlabItemTable(ChiseledBlocks.MOSSY_MUD_TILE_SLAB));
        dropSelf(ChiseledBlocks.MOSSY_MUD_TILE_WALL);

        dropSelf(ChiseledBlocks.HONEYCOMB_STAIRS);
        add(ChiseledBlocks.HONEYCOMB_SLAB, createSlabItemTable(ChiseledBlocks.HONEYCOMB_SLAB));
        dropSelf(ChiseledBlocks.HONEYCOMB_WALL);
        dropSelf(ChiseledBlocks.HONEYCOMB_BRICKS);
        dropSelf(ChiseledBlocks.HONEYCOMB_BRICK_STAIRS);
        add(ChiseledBlocks.HONEYCOMB_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.HONEYCOMB_BRICK_SLAB));
        dropSelf(ChiseledBlocks.HONEYCOMB_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_HONEYCOMB_BRICKS);
        dropSelf(ChiseledBlocks.CUT_HONEYCOMB_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_HONEYCOMB_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_HONEYCOMB_BRICK_SLAB));
        dropSelf(ChiseledBlocks.HONEYCOMB_TILES);
        dropSelf(ChiseledBlocks.HONEYCOMB_TILE_STAIRS);
        add(ChiseledBlocks.HONEYCOMB_TILE_SLAB, createSlabItemTable(ChiseledBlocks.HONEYCOMB_TILE_SLAB));
        dropSelf(ChiseledBlocks.HONEYCOMB_TILE_WALL);

        dropSelf(ChiseledBlocks.SMOOTH_SANDSTONE_WALL);
        dropSelf(ChiseledBlocks.SANDSTONE_BRICKS);
        dropSelf(ChiseledBlocks.SANDSTONE_BRICK_STAIRS);
        add(ChiseledBlocks.SANDSTONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.SANDSTONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.SANDSTONE_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_SANDSTONE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_SANDSTONE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_SANDSTONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_SANDSTONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.SANDSTONE_TILES);
        dropSelf(ChiseledBlocks.SANDSTONE_TILE_STAIRS);
        add(ChiseledBlocks.SANDSTONE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.SANDSTONE_TILE_SLAB));
        dropSelf(ChiseledBlocks.SANDSTONE_TILE_WALL);

        dropSelf(ChiseledBlocks.SMOOTH_RED_SANDSTONE_WALL);
        dropSelf(ChiseledBlocks.RED_SANDSTONE_BRICKS);
        dropSelf(ChiseledBlocks.RED_SANDSTONE_BRICK_STAIRS);
        add(ChiseledBlocks.RED_SANDSTONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.RED_SANDSTONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.RED_SANDSTONE_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_RED_SANDSTONE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_RED_SANDSTONE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_RED_SANDSTONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_RED_SANDSTONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.RED_SANDSTONE_TILES);
        dropSelf(ChiseledBlocks.RED_SANDSTONE_TILE_STAIRS);
        add(ChiseledBlocks.RED_SANDSTONE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.RED_SANDSTONE_TILE_SLAB));
        dropSelf(ChiseledBlocks.RED_SANDSTONE_TILE_WALL);

        dropSelf(ChiseledBlocks.PRISMARINE_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_PRISMARINE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_PRISMARINE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_PRISMARINE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_PRISMARINE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.DARK_PRISMARINE_WALL);
        dropSelf(ChiseledBlocks.DARK_PRISMARINE_BRICKS);
        dropSelf(ChiseledBlocks.DARK_PRISMARINE_BRICK_STAIRS);
        add(ChiseledBlocks.DARK_PRISMARINE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.DARK_PRISMARINE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.DARK_PRISMARINE_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICK_SLAB));

        dropSelf(ChiseledBlocks.PACKED_SNOW_BRICKS);
        dropSelf(ChiseledBlocks.PACKED_SNOW_BRICK_STAIRS);
        add(ChiseledBlocks.PACKED_SNOW_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.PACKED_SNOW_BRICK_SLAB));
        dropSelf(ChiseledBlocks.CUT_PACKED_SNOW_BRICKS);
        dropSelf(ChiseledBlocks.CUT_PACKED_SNOW_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_PACKED_SNOW_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_PACKED_SNOW_BRICK_SLAB));
        dropSelf(ChiseledBlocks.PACKED_SNOW_TILES);
        dropSelf(ChiseledBlocks.PACKED_SNOW_TILE_STAIRS);
        add(ChiseledBlocks.PACKED_SNOW_TILE_SLAB, createSlabItemTable(ChiseledBlocks.PACKED_SNOW_TILE_SLAB));

        dropSelf(ChiseledBlocks.TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.WHITE_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.GRAY_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.BLACK_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.BROWN_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.RED_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.RED_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.RED_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.RED_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.RED_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.ORANGE_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.YELLOW_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.LIME_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.LIME_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.LIME_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.LIME_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.LIME_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.GREEN_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.CYAN_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.BLUE_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.PURPLE_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_WALL);
        dropSelf(ChiseledBlocks.PINK_TERRACOTTA_BRICKS);
        dropSelf(ChiseledBlocks.PINK_TERRACOTTA_BRICK_STAIRS);
        add(ChiseledBlocks.PINK_TERRACOTTA_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.PINK_TERRACOTTA_BRICK_SLAB));
        dropSelf(ChiseledBlocks.PINK_TERRACOTTA_BRICK_WALL);

        dropSelf(ChiseledBlocks.CRACKED_RED_NETHER_BRICKS);
        dropSelf(ChiseledBlocks.RED_NETHER_BRICK_FENCE);
        dropSelf(ChiseledBlocks.CHISELED_RED_NETHER_BRICKS);

        dropSelf(ChiseledBlocks.SMOOTH_BASALT_STAIRS);
        add(ChiseledBlocks.SMOOTH_BASALT_SLAB, createSlabItemTable(ChiseledBlocks.SMOOTH_BASALT_SLAB));
        dropSelf(ChiseledBlocks.SMOOTH_BASALT_WALL);
        dropSelf(ChiseledBlocks.BASALT_BRICKS);
        dropSelf(ChiseledBlocks.BASALT_BRICK_STAIRS);
        add(ChiseledBlocks.BASALT_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.BASALT_BRICK_SLAB));
        dropSelf(ChiseledBlocks.BASALT_BRICK_WALL);
        dropSelf(ChiseledBlocks.CUT_BASALT_BRICKS);
        dropSelf(ChiseledBlocks.CUT_BASALT_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_BASALT_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_BASALT_BRICK_SLAB));
        dropSelf(ChiseledBlocks.BASALT_TILES);
        dropSelf(ChiseledBlocks.BASALT_TILE_STAIRS);
        add(ChiseledBlocks.BASALT_TILE_SLAB, createSlabItemTable(ChiseledBlocks.BASALT_TILE_SLAB));
        dropSelf(ChiseledBlocks.BASALT_TILE_WALL);

        dropSelf(ChiseledBlocks.CUT_POLISHED_BLACKSTONE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_CUT_POLISHED_BLACKSTONE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_POLISHED_BLACKSTONE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_POLISHED_BLACKSTONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_POLISHED_BLACKSTONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_BLACKSTONE_TILES);
        dropSelf(ChiseledBlocks.CRACKED_POLISHED_BLACKSTONE_TILES);
        dropSelf(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_STAIRS);
        add(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_WALL);

        dropSelf(ChiseledBlocks.END_STONE_STAIRS);
        add(ChiseledBlocks.END_STONE_SLAB, createSlabItemTable(ChiseledBlocks.END_STONE_SLAB));
        dropSelf(ChiseledBlocks.END_STONE_WALL);
        dropSelf(ChiseledBlocks.POLISHED_END_STONE);
        dropSelf(ChiseledBlocks.POLISHED_END_STONE_STAIRS);
        add(ChiseledBlocks.POLISHED_END_STONE_SLAB, createSlabItemTable(ChiseledBlocks.POLISHED_END_STONE_SLAB));
        dropSelf(ChiseledBlocks.POLISHED_END_STONE_WALL);
        dropSelf(ChiseledBlocks.CRACKED_END_STONE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_END_STONE_BRICKS);
        dropSelf(ChiseledBlocks.CRACKED_CUT_END_STONE_BRICKS);
        dropSelf(ChiseledBlocks.CUT_END_STONE_BRICK_STAIRS);
        add(ChiseledBlocks.CUT_END_STONE_BRICK_SLAB, createSlabItemTable(ChiseledBlocks.CUT_END_STONE_BRICK_SLAB));
        dropSelf(ChiseledBlocks.END_STONE_TILES);
        dropSelf(ChiseledBlocks.CRACKED_END_STONE_TILES);
        dropSelf(ChiseledBlocks.END_STONE_TILE_STAIRS);
        add(ChiseledBlocks.END_STONE_TILE_SLAB, createSlabItemTable(ChiseledBlocks.END_STONE_TILE_SLAB));
        dropSelf(ChiseledBlocks.END_STONE_TILE_WALL);

        dropSelf(ChiseledBlocks.NETHERITE_STAIRS);
    }
}