package net.hyper.chiseled.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.hyper.chiseled.registry.ChiseledBlocks;
import net.minecraft.core.HolderLookup;
import java.util.concurrent.CompletableFuture;

public class ChiseledLangGen extends FabricLanguageProvider {
    public ChiseledLangGen(FabricPackOutput dataOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
        super(dataOutput, registryLookup);
    }

    public void generateTranslations(HolderLookup.Provider registryLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add(ChiseledBlocks.OAK_TRIM, "Oak Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_OAK_PLANKS, "Vertical Oak Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_OAK_STAIRS, "Vertical Oak Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_OAK_SLAB, "Vertical Oak Slab");
        translationBuilder.add(ChiseledBlocks.SPRUCE_TRIM, "Spruce Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_SPRUCE_PLANKS, "Vertical Spruce Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_SPRUCE_STAIRS, "Vertical Spruce Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_SPRUCE_SLAB, "Vertical Spruce Slab");
        translationBuilder.add(ChiseledBlocks.BIRCH_TRIM, "Birch Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_BIRCH_PLANKS, "Vertical Birch Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_BIRCH_STAIRS, "Vertical Birch Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_BIRCH_SLAB, "Vertical Birch Slab");
        translationBuilder.add(ChiseledBlocks.JUNGLE_TRIM, "Jungle Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_JUNGLE_PLANKS, "Vertical Jungle Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_JUNGLE_STAIRS, "Vertical Jungle Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_JUNGLE_SLAB, "Vertical Jungle Slab");
        translationBuilder.add(ChiseledBlocks.ACACIA_TRIM, "Acacia Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_ACACIA_PLANKS, "Vertical Acacia Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_ACACIA_STAIRS, "Vertical Acacia Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_ACACIA_SLAB, "Vertical Acacia Slab");
        translationBuilder.add(ChiseledBlocks.DARK_OAK_TRIM, "Dark Oak Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_DARK_OAK_PLANKS, "Vertical Dark Oak Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_DARK_OAK_STAIRS, "Vertical Dark Oak Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_DARK_OAK_SLAB, "Vertical Dark Oak Slab");
        translationBuilder.add(ChiseledBlocks.MANGROVE_TRIM, "Mangrove Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_MANGROVE_PLANKS, "Vertical Mangrove Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_MANGROVE_STAIRS, "Vertical Mangrove Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_MANGROVE_SLAB, "Vertical Mangrove Slab");
        translationBuilder.add(ChiseledBlocks.CHERRY_TRIM, "Cherry Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_CHERRY_PLANKS, "Vertical Cherry Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_CHERRY_STAIRS, "Vertical Cherry Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_CHERRY_SLAB, "Vertical Cherry Slab");
        translationBuilder.add(ChiseledBlocks.PALE_OAK_TRIM, "Pale Oak Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_PALE_OAK_PLANKS, "Vertical Pale Oak Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_PALE_OAK_STAIRS, "Vertical Pale Oak Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_PALE_OAK_SLAB, "Vertical Pale Oak Slab");
        translationBuilder.add(ChiseledBlocks.BAMBOO_TRIM, "Bamboo Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_BAMBOO_PLANKS, "Vertical Bamboo Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_BAMBOO_STAIRS, "Vertical Bamboo Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_BAMBOO_SLAB, "Vertical Bamboo Slab");
        translationBuilder.add(ChiseledBlocks.CRIMSON_TRIM, "Crimson Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_CRIMSON_PLANKS, "Vertical Crimson Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_CRIMSON_STAIRS, "Vertical Crimson Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_CRIMSON_SLAB, "Vertical Crimson Slab");
        translationBuilder.add(ChiseledBlocks.WARPED_TRIM, "Warped Trim");
        translationBuilder.add(ChiseledBlocks.VERTICAL_WARPED_PLANKS, "Vertical Warped Planks");
        translationBuilder.add(ChiseledBlocks.VERTICAL_WARPED_STAIRS, "Vertical Warped Stairs");
        translationBuilder.add(ChiseledBlocks.VERTICAL_WARPED_SLAB, "Vertical Warped Slab");

        translationBuilder.add(ChiseledBlocks.STONE_WALL, "Stone Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_STONE, "Polished Stone");
        translationBuilder.add(ChiseledBlocks.POLISHED_STONE_STAIRS, "Polished Stone Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_STONE_SLAB, "Polished Stone Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_STONE_WALL, "Polished Stone Wall");
        translationBuilder.add(ChiseledBlocks.SMOOTH_STONE_STAIRS, "Smooth Stone Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_CHISELED_STONE_BRICKS, "Mossy Chiseled Stone Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_STONE_BRICKS, "Cut Stone Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_STONE_BRICKS, "Cracked Cut Stone Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_STONE_BRICK_STAIRS, "Cut Stone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_STONE_BRICK_SLAB, "Cut Stone Brick Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_STONE_BRICKS, "Mossy Cut Stone Bricks");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_STONE_BRICK_STAIRS, "Mossy Cut Stone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_STONE_BRICK_SLAB, "Mossy Cut Stone Brick Slab");
        translationBuilder.add(ChiseledBlocks.STONE_TILES, "Stone Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_STONE_TILES, "Cracked Stone Tiles");
        translationBuilder.add(ChiseledBlocks.STONE_TILE_STAIRS, "Stone Tile Stairs");
        translationBuilder.add(ChiseledBlocks.STONE_TILE_SLAB, "Stone Tile Slab");
        translationBuilder.add(ChiseledBlocks.STONE_TILE_WALL, "Stone Tile Wall");
        translationBuilder.add(ChiseledBlocks.MOSSY_STONE_TILES, "Mossy Stone Tiles");
        translationBuilder.add(ChiseledBlocks.MOSSY_STONE_TILE_STAIRS, "Mossy Stone Tile Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_STONE_TILE_SLAB, "Mossy Stone Tile Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_STONE_TILE_WALL, "Mossy Stone Tile Wall");

        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_WALL, "Polished Granite Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_BRICKS, "Polished Granite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_GRANITE_BRICKS, "Cracked Polished Granite Bricks");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_BRICK_STAIRS, "Polished Granite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_BRICK_SLAB, "Polished Granite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_BRICK_WALL, "Polished Granite Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICKS, "Cut Polished Granite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_POLISHED_GRANITE_BRICKS, "Cracked Cut Polished Granite Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICK_STAIRS, "Cut Polished Granite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICK_SLAB, "Cut Polished Granite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_TILES, "Polished Granite Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_GRANITE_TILES, "Cracked Polished Granite Tiles");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_TILE_STAIRS, "Polished Granite Tile Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_TILE_SLAB, "Polished Granite Tile Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_TILE_WALL, "Polished Granite Tile Wall");

        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_WALL, "Polished Diorite Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_BRICKS, "Polished Diorite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_DIORITE_BRICKS, "Cracked Polished Diorite Bricks");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_BRICK_STAIRS, "Polished Diorite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_BRICK_SLAB, "Polished Diorite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_BRICK_WALL, "Polished Diorite Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICKS, "Cut Polished Diorite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_POLISHED_DIORITE_BRICKS, "Cracked Cut Polished Diorite Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICK_STAIRS, "Cut Polished Diorite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICK_SLAB, "Cut Polished Diorite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_TILES, "Polished Diorite Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_DIORITE_TILES, "Cracked Polished Diorite Tiles");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_TILE_STAIRS, "Polished Diorite Tile Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_TILE_SLAB, "Polished Diorite Tile Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_TILE_WALL, "Polished Diorite Tile Wall");

        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_WALL, "Polished Andesite Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_BRICKS, "Polished Andesite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_BRICKS, "Cracked Polished Andesite Bricks");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_STAIRS, "Polished Andesite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_SLAB, "Polished Andesite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_WALL, "Polished Andesite Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICKS, "Cut Polished Andesite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_POLISHED_ANDESITE_BRICKS, "Cracked Cut Polished Andesite Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICK_STAIRS, "Cut Polished Andesite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICK_SLAB, "Cut Polished Andesite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_TILES, "Polished Andesite Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_TILES, "Cracked Polished Andesite Tiles");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_TILE_STAIRS, "Polished Andesite Tile Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_TILE_SLAB, "Polished Andesite Tile Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_TILE_WALL, "Polished Andesite Tile Wall");

        translationBuilder.add(ChiseledBlocks.CUT_DEEPSLATE_BRICKS, "Cut Deepslate Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_DEEPSLATE_BRICKS, "Cracked Cut Deepslate Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_DEEPSLATE_BRICK_STAIRS, "Cut Deepslate Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_DEEPSLATE_BRICK_SLAB, "Cut Deepslate Brick Slab");

        translationBuilder.add(ChiseledBlocks.CALCITE_STAIRS, "Calcite Stairs");
        translationBuilder.add(ChiseledBlocks.CALCITE_SLAB, "Calcite Slab");
        translationBuilder.add(ChiseledBlocks.CALCITE_WALL, "Calcite Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_CALCITE, "Polished Calcite");
        translationBuilder.add(ChiseledBlocks.POLISHED_CALCITE_STAIRS, "Polished Calcite Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_CALCITE_SLAB, "Polished Calcite Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_CALCITE_WALL, "Polished Calcite Wall");
        translationBuilder.add(ChiseledBlocks.CALCITE_BRICKS, "Calcite Bricks");
        translationBuilder.add(ChiseledBlocks.CALCITE_BRICK_STAIRS, "Calcite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CALCITE_BRICK_SLAB, "Calcite Brick Slab");
        translationBuilder.add(ChiseledBlocks.CALCITE_BRICK_WALL, "Calcite Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_CALCITE_BRICKS, "Cut Calcite Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_CALCITE_BRICK_STAIRS, "Cut Calcite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_CALCITE_BRICK_SLAB, "Cut Calcite Brick Slab");
        translationBuilder.add(ChiseledBlocks.CALCITE_TILES, "Calcite Tiles");
        translationBuilder.add(ChiseledBlocks.CALCITE_TILE_STAIRS, "Calcite Tile Stairs");
        translationBuilder.add(ChiseledBlocks.CALCITE_TILE_SLAB, "Calcite Tile Slab");
        translationBuilder.add(ChiseledBlocks.CALCITE_TILE_WALL, "Calcite Tile Wall");

        translationBuilder.add(ChiseledBlocks.DRIPSTONE_STAIRS, "Dripstone Stairs");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_SLAB, "Dripstone Slab");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_WALL, "Dripstone Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_DRIPSTONE, "Polished Dripstone");
        translationBuilder.add(ChiseledBlocks.POLISHED_DRIPSTONE_STAIRS, "Polished Dripstone Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_DRIPSTONE_SLAB, "Polished Dripstone Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_DRIPSTONE_WALL, "Polished Dripstone Wall");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_BRICKS, "Dripstone Bricks");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_BRICK_STAIRS, "Dripstone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_BRICK_SLAB, "Dripstone Brick Slab");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_BRICK_WALL, "Dripstone Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_DRIPSTONE_BRICKS, "Cut Dripstone Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_DRIPSTONE_BRICK_STAIRS, "Cut Dripstone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_DRIPSTONE_BRICK_SLAB, "Cut Dripstone Brick Slab");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_TILES, "Dripstone Tiles");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_TILE_STAIRS, "Dripstone Tile Stairs");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_TILE_SLAB, "Dripstone Tile Slab");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_TILE_WALL, "Dripstone Tile Wall");

        translationBuilder.add(ChiseledBlocks.MIXED_BRICKS, "Mixed Bricks");
        translationBuilder.add(ChiseledBlocks.MIXED_BRICK_STAIRS, "Mixed Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MIXED_BRICK_SLAB, "Mixed Brick Slab");
        translationBuilder.add(ChiseledBlocks.MIXED_BRICK_WALL, "Mixed Brick Wall");
        translationBuilder.add(ChiseledBlocks.MOSSY_BRICKS, "Mossy Bricks");
        translationBuilder.add(ChiseledBlocks.MOSSY_BRICK_STAIRS, "Mossy Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_BRICK_SLAB, "Mossy Brick Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_BRICK_WALL, "Mossy Brick Wall");

        translationBuilder.add(ChiseledBlocks.PACKED_MUD_STAIRS, "Packed Mud Stairs");
        translationBuilder.add(ChiseledBlocks.PACKED_MUD_SLAB, "Packed Mud Slab");
        translationBuilder.add(ChiseledBlocks.PACKED_MUD_WALL, "Packed Mud Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_MUD, "Polished Mud");
        translationBuilder.add(ChiseledBlocks.POLISHED_MUD_STAIRS, "Polished Mud Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_MUD_SLAB, "Polished Mud Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_MUD_WALL, "Polished Mud Wall");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_BRICKS, "Mossy Mud Bricks");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_BRICK_STAIRS, "Mossy Mud Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_BRICK_SLAB, "Mossy Mud Brick Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_BRICK_WALL, "Mossy Mud Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_MUD_BRICKS, "Cut Mud Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_MUD_BRICK_STAIRS, "Cut Mud Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_MUD_BRICK_SLAB, "Cut Mud Brick Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_MUD_BRICKS, "Mossy Cut Mud Bricks");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_MUD_BRICK_STAIRS, "Mossy Cut Mud Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_MUD_BRICK_SLAB, "Mossy Cut Mud Brick Slab");
        translationBuilder.add(ChiseledBlocks.MUD_TILES, "Mud Tiles");
        translationBuilder.add(ChiseledBlocks.MUD_TILE_STAIRS, "Mud Tile Stairs");
        translationBuilder.add(ChiseledBlocks.MUD_TILE_SLAB, "Mud Tile Slab");
        translationBuilder.add(ChiseledBlocks.MUD_TILE_WALL, "Mud Tile Wall");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_TILES, "Mossy Mud Tiles");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_TILE_STAIRS, "Mossy Mud Tile Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_TILE_SLAB, "Mossy Mud Tile Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_TILE_WALL, "Mossy Mud Tile Wall");

        translationBuilder.add("itemgroup.chiseled.chiseled", "Chiseled");
        translationBuilder.add("text.chiseled.asset_overrides", "Asset Overrides");
        translationBuilder.add("text.chiseled.data_overrides", "Data Overrides");
    }
}