package net.hyper.chiseled.datagen;

import net.fabricmc.fabric.api.client.datagen.v1.provider.FabricModelProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.hyper.chiseled.registry.ChiseledBlocks;
import net.hyper.silliestlib.utils.SilliestLibDataUtils;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.world.level.block.Blocks;

public class ChiseledModelGen extends FabricModelProvider {
    public ChiseledModelGen(FabricPackOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators blockModelGenerators) {
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.STONE_WALL, Blocks.STONE, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider polishedStonePool = blockModelGenerators.family(ChiseledBlocks.POLISHED_STONE);
        polishedStonePool.stairs(ChiseledBlocks.POLISHED_STONE_STAIRS);
        polishedStonePool.slab(ChiseledBlocks.POLISHED_STONE_SLAB);
        polishedStonePool.wall(ChiseledBlocks.POLISHED_STONE_WALL);
        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.SMOOTH_STONE_STAIRS, Blocks.SMOOTH_STONE, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider cutStoneBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_STONE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_CUT_STONE_BRICKS);
        cutStoneBrickPool.stairs(ChiseledBlocks.CUT_STONE_BRICK_STAIRS);
        cutStoneBrickPool.slab(ChiseledBlocks.CUT_STONE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider mossyCutStoneBrickPool = blockModelGenerators.family(ChiseledBlocks.MOSSY_CUT_STONE_BRICKS);
        mossyCutStoneBrickPool.stairs(ChiseledBlocks.MOSSY_CUT_STONE_BRICK_STAIRS);
        mossyCutStoneBrickPool.slab(ChiseledBlocks.MOSSY_CUT_STONE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider stoneTilePool = blockModelGenerators.family(ChiseledBlocks.STONE_TILES);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_STONE_TILES);
        stoneTilePool.stairs(ChiseledBlocks.STONE_TILE_STAIRS);
        stoneTilePool.slab(ChiseledBlocks.STONE_TILE_SLAB);
        stoneTilePool.wall(ChiseledBlocks.STONE_TILE_WALL);
        BlockModelGenerators.BlockFamilyProvider mossyStoneTilePool = blockModelGenerators.family(ChiseledBlocks.MOSSY_STONE_TILES);
        mossyStoneTilePool.stairs(ChiseledBlocks.MOSSY_STONE_TILE_STAIRS);
        mossyStoneTilePool.slab(ChiseledBlocks.MOSSY_STONE_TILE_SLAB);
        mossyStoneTilePool.wall(ChiseledBlocks.MOSSY_STONE_TILE_WALL);

        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.POLISHED_GRANITE_WALL, Blocks.POLISHED_GRANITE, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider polishedGraniteBrickPool = blockModelGenerators.family(ChiseledBlocks.POLISHED_GRANITE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_POLISHED_GRANITE_BRICKS);
        polishedGraniteBrickPool.stairs(ChiseledBlocks.POLISHED_GRANITE_BRICK_STAIRS);
        polishedGraniteBrickPool.slab(ChiseledBlocks.POLISHED_GRANITE_BRICK_SLAB);
        polishedGraniteBrickPool.wall(ChiseledBlocks.POLISHED_GRANITE_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutPolishedGraniteBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_CUT_POLISHED_GRANITE_BRICKS);
        cutPolishedGraniteBrickPool.stairs(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICK_STAIRS);
        cutPolishedGraniteBrickPool.slab(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider polishedGraniteTilePool = blockModelGenerators.family(ChiseledBlocks.POLISHED_GRANITE_TILES);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_POLISHED_GRANITE_TILES);
        polishedGraniteTilePool.stairs(ChiseledBlocks.POLISHED_GRANITE_TILE_STAIRS);
        polishedGraniteTilePool.slab(ChiseledBlocks.POLISHED_GRANITE_TILE_SLAB);
        polishedGraniteTilePool.wall(ChiseledBlocks.POLISHED_GRANITE_TILE_WALL);

        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.POLISHED_DIORITE_WALL, Blocks.POLISHED_DIORITE, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider polishedDioriteBrickPool = blockModelGenerators.family(ChiseledBlocks.POLISHED_DIORITE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_POLISHED_DIORITE_BRICKS);
        polishedDioriteBrickPool.stairs(ChiseledBlocks.POLISHED_DIORITE_BRICK_STAIRS);
        polishedDioriteBrickPool.slab(ChiseledBlocks.POLISHED_DIORITE_BRICK_SLAB);
        polishedDioriteBrickPool.wall(ChiseledBlocks.POLISHED_DIORITE_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutPolishedDioriteBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_CUT_POLISHED_DIORITE_BRICKS);
        cutPolishedDioriteBrickPool.stairs(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICK_STAIRS);
        cutPolishedDioriteBrickPool.slab(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider polishedDioriteTilePool = blockModelGenerators.family(ChiseledBlocks.POLISHED_DIORITE_TILES);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_POLISHED_DIORITE_TILES);
        polishedDioriteTilePool.stairs(ChiseledBlocks.POLISHED_DIORITE_TILE_STAIRS);
        polishedDioriteTilePool.slab(ChiseledBlocks.POLISHED_DIORITE_TILE_SLAB);
        polishedDioriteTilePool.wall(ChiseledBlocks.POLISHED_DIORITE_TILE_WALL);

        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.POLISHED_ANDESITE_WALL, Blocks.POLISHED_ANDESITE, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider polishedAndesiteBrickPool = blockModelGenerators.family(ChiseledBlocks.POLISHED_ANDESITE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_BRICKS);
        polishedAndesiteBrickPool.stairs(ChiseledBlocks.POLISHED_ANDESITE_BRICK_STAIRS);
        polishedAndesiteBrickPool.slab(ChiseledBlocks.POLISHED_ANDESITE_BRICK_SLAB);
        polishedAndesiteBrickPool.wall(ChiseledBlocks.POLISHED_ANDESITE_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutPolishedAndesiteBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_CUT_POLISHED_ANDESITE_BRICKS);
        cutPolishedAndesiteBrickPool.stairs(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICK_STAIRS);
        cutPolishedAndesiteBrickPool.slab(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider polishedAndesiteTilePool = blockModelGenerators.family(ChiseledBlocks.POLISHED_ANDESITE_TILES);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_TILES);
        polishedAndesiteTilePool.stairs(ChiseledBlocks.POLISHED_ANDESITE_TILE_STAIRS);
        polishedAndesiteTilePool.slab(ChiseledBlocks.POLISHED_ANDESITE_TILE_SLAB);
        polishedAndesiteTilePool.wall(ChiseledBlocks.POLISHED_ANDESITE_TILE_WALL);

        BlockModelGenerators.BlockFamilyProvider cutDeepslateBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_DEEPSLATE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_CUT_DEEPSLATE_BRICKS);
        cutDeepslateBrickPool.stairs(ChiseledBlocks.CUT_DEEPSLATE_BRICK_STAIRS);
        cutDeepslateBrickPool.slab(ChiseledBlocks.CUT_DEEPSLATE_BRICK_SLAB);

        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.CALCITE_STAIRS, Blocks.CALCITE, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneSlab(ChiseledBlocks.CALCITE_SLAB, Blocks.CALCITE, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.CALCITE_WALL, Blocks.CALCITE, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider polishedCalcitePool = blockModelGenerators.family(ChiseledBlocks.POLISHED_CALCITE);
        polishedCalcitePool.stairs(ChiseledBlocks.POLISHED_CALCITE_STAIRS);
        polishedCalcitePool.slab(ChiseledBlocks.POLISHED_CALCITE_SLAB);
        polishedCalcitePool.wall(ChiseledBlocks.POLISHED_CALCITE_WALL);
        BlockModelGenerators.BlockFamilyProvider calciteBrickPool = blockModelGenerators.family(ChiseledBlocks.CALCITE_BRICKS);
        calciteBrickPool.stairs(ChiseledBlocks.CALCITE_BRICK_STAIRS);
        calciteBrickPool.slab(ChiseledBlocks.CALCITE_BRICK_SLAB);
        calciteBrickPool.wall(ChiseledBlocks.CALCITE_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutCalciteBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_CALCITE_BRICKS);
        cutCalciteBrickPool.stairs(ChiseledBlocks.CUT_CALCITE_BRICK_STAIRS);
        cutCalciteBrickPool.slab(ChiseledBlocks.CUT_CALCITE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider calciteTilePool = blockModelGenerators.family(ChiseledBlocks.CALCITE_TILES);
        calciteTilePool.stairs(ChiseledBlocks.CALCITE_TILE_STAIRS);
        calciteTilePool.slab(ChiseledBlocks.CALCITE_TILE_SLAB);
        calciteTilePool.wall(ChiseledBlocks.CALCITE_TILE_WALL);

        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.DRIPSTONE_STAIRS, Blocks.DRIPSTONE_BLOCK, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneSlab(ChiseledBlocks.DRIPSTONE_SLAB, Blocks.DRIPSTONE_BLOCK, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.DRIPSTONE_WALL, Blocks.DRIPSTONE_BLOCK, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider polishedDripstonePool = blockModelGenerators.family(ChiseledBlocks.POLISHED_DRIPSTONE);
        polishedDripstonePool.stairs(ChiseledBlocks.POLISHED_DRIPSTONE_STAIRS);
        polishedDripstonePool.slab(ChiseledBlocks.POLISHED_DRIPSTONE_SLAB);
        polishedDripstonePool.wall(ChiseledBlocks.POLISHED_DRIPSTONE_WALL);
        BlockModelGenerators.BlockFamilyProvider dripstoneBrickPool = blockModelGenerators.family(ChiseledBlocks.DRIPSTONE_BRICKS);
        dripstoneBrickPool.stairs(ChiseledBlocks.DRIPSTONE_BRICK_STAIRS);
        dripstoneBrickPool.slab(ChiseledBlocks.DRIPSTONE_BRICK_SLAB);
        dripstoneBrickPool.wall(ChiseledBlocks.DRIPSTONE_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutDripstoneBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_DRIPSTONE_BRICKS);
        cutDripstoneBrickPool.stairs(ChiseledBlocks.CUT_DRIPSTONE_BRICK_STAIRS);
        cutDripstoneBrickPool.slab(ChiseledBlocks.CUT_DRIPSTONE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider dripstoneTilePool = blockModelGenerators.family(ChiseledBlocks.DRIPSTONE_TILES);
        dripstoneTilePool.stairs(ChiseledBlocks.DRIPSTONE_TILE_STAIRS);
        dripstoneTilePool.slab(ChiseledBlocks.DRIPSTONE_TILE_SLAB);
        dripstoneTilePool.wall(ChiseledBlocks.DRIPSTONE_TILE_WALL);

        BlockModelGenerators.BlockFamilyProvider mixedBrickPool = blockModelGenerators.family(ChiseledBlocks.MIXED_BRICKS);
        mixedBrickPool.stairs(ChiseledBlocks.MIXED_BRICK_STAIRS);
        mixedBrickPool.slab(ChiseledBlocks.MIXED_BRICK_SLAB);
        mixedBrickPool.wall(ChiseledBlocks.MIXED_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider mossyBrickPool = blockModelGenerators.family(ChiseledBlocks.MOSSY_BRICKS);
        mossyBrickPool.stairs(ChiseledBlocks.MOSSY_BRICK_STAIRS);
        mossyBrickPool.slab(ChiseledBlocks.MOSSY_BRICK_SLAB);
        mossyBrickPool.wall(ChiseledBlocks.MOSSY_BRICK_WALL);

        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.PACKED_MUD_STAIRS, Blocks.PACKED_MUD, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneSlab(ChiseledBlocks.PACKED_MUD_SLAB, Blocks.PACKED_MUD, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.PACKED_MUD_WALL, Blocks.PACKED_MUD, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider polishedMudPool = blockModelGenerators.family(ChiseledBlocks.POLISHED_MUD);
        polishedMudPool.stairs(ChiseledBlocks.POLISHED_MUD_STAIRS);
        polishedMudPool.slab(ChiseledBlocks.POLISHED_MUD_SLAB);
        polishedMudPool.wall(ChiseledBlocks.POLISHED_MUD_WALL);
        BlockModelGenerators.BlockFamilyProvider mossyMudBrickPool = blockModelGenerators.family(ChiseledBlocks.MOSSY_MUD_BRICKS);
        mossyMudBrickPool.stairs(ChiseledBlocks.MOSSY_MUD_BRICK_STAIRS);
        mossyMudBrickPool.slab(ChiseledBlocks.MOSSY_MUD_BRICK_SLAB);
        mossyMudBrickPool.wall(ChiseledBlocks.MOSSY_MUD_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutMudBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_MUD_BRICKS);
        cutMudBrickPool.stairs(ChiseledBlocks.CUT_MUD_BRICK_STAIRS);
        cutMudBrickPool.slab(ChiseledBlocks.CUT_MUD_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider mossyCutMudBrickPool = blockModelGenerators.family(ChiseledBlocks.MOSSY_CUT_MUD_BRICKS);
        mossyCutMudBrickPool.stairs(ChiseledBlocks.MOSSY_CUT_MUD_BRICK_STAIRS);
        mossyCutMudBrickPool.slab(ChiseledBlocks.MOSSY_CUT_MUD_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider mudTilePool = blockModelGenerators.family(ChiseledBlocks.MUD_TILES);
        mudTilePool.stairs(ChiseledBlocks.MUD_TILE_STAIRS);
        mudTilePool.slab(ChiseledBlocks.MUD_TILE_SLAB);
        mudTilePool.wall(ChiseledBlocks.MUD_TILE_WALL);
        BlockModelGenerators.BlockFamilyProvider mossyMudTilePool = blockModelGenerators.family(ChiseledBlocks.MOSSY_MUD_TILES);
        mossyMudTilePool.stairs(ChiseledBlocks.MOSSY_MUD_TILE_STAIRS);
        mossyMudTilePool.slab(ChiseledBlocks.MOSSY_MUD_TILE_SLAB);
        mossyMudTilePool.wall(ChiseledBlocks.MOSSY_MUD_TILE_WALL);

        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.HONEYCOMB_STAIRS, Blocks.HONEYCOMB_BLOCK, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneSlab(ChiseledBlocks.HONEYCOMB_SLAB, Blocks.HONEYCOMB_BLOCK, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.HONEYCOMB_WALL, Blocks.HONEYCOMB_BLOCK, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider honeycombBrickPool = blockModelGenerators.family(ChiseledBlocks.HONEYCOMB_BRICKS);
        honeycombBrickPool.stairs(ChiseledBlocks.HONEYCOMB_BRICK_STAIRS);
        honeycombBrickPool.slab(ChiseledBlocks.HONEYCOMB_BRICK_SLAB);
        honeycombBrickPool.wall(ChiseledBlocks.HONEYCOMB_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutHoneycombBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_HONEYCOMB_BRICKS);
        cutHoneycombBrickPool.stairs(ChiseledBlocks.CUT_HONEYCOMB_BRICK_STAIRS);
        cutHoneycombBrickPool.slab(ChiseledBlocks.CUT_HONEYCOMB_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider honeycombTilePool = blockModelGenerators.family(ChiseledBlocks.HONEYCOMB_TILES);
        honeycombTilePool.stairs(ChiseledBlocks.HONEYCOMB_TILE_STAIRS);
        honeycombTilePool.slab(ChiseledBlocks.HONEYCOMB_TILE_SLAB);
        honeycombTilePool.wall(ChiseledBlocks.HONEYCOMB_TILE_WALL);
        
        BlockModelGenerators.BlockFamilyProvider sandstoneBrickPool = blockModelGenerators.family(ChiseledBlocks.SANDSTONE_BRICKS);
        sandstoneBrickPool.stairs(ChiseledBlocks.SANDSTONE_BRICK_STAIRS);
        sandstoneBrickPool.slab(ChiseledBlocks.SANDSTONE_BRICK_SLAB);
        sandstoneBrickPool.wall(ChiseledBlocks.SANDSTONE_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutSandstoneBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_SANDSTONE_BRICKS);
        cutSandstoneBrickPool.stairs(ChiseledBlocks.CUT_SANDSTONE_BRICK_STAIRS);
        cutSandstoneBrickPool.slab(ChiseledBlocks.CUT_SANDSTONE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider sandstoneTilePool = blockModelGenerators.family(ChiseledBlocks.SANDSTONE_TILES);
        sandstoneTilePool.stairs(ChiseledBlocks.SANDSTONE_TILE_STAIRS);
        sandstoneTilePool.slab(ChiseledBlocks.SANDSTONE_TILE_SLAB);
        sandstoneTilePool.wall(ChiseledBlocks.SANDSTONE_TILE_WALL);

        BlockModelGenerators.BlockFamilyProvider redSandstoneBrickPool = blockModelGenerators.family(ChiseledBlocks.RED_SANDSTONE_BRICKS);
        redSandstoneBrickPool.stairs(ChiseledBlocks.RED_SANDSTONE_BRICK_STAIRS);
        redSandstoneBrickPool.slab(ChiseledBlocks.RED_SANDSTONE_BRICK_SLAB);
        redSandstoneBrickPool.wall(ChiseledBlocks.RED_SANDSTONE_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutRedSandstoneBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_RED_SANDSTONE_BRICKS);
        cutRedSandstoneBrickPool.stairs(ChiseledBlocks.CUT_RED_SANDSTONE_BRICK_STAIRS);
        cutRedSandstoneBrickPool.slab(ChiseledBlocks.CUT_RED_SANDSTONE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider redSandstoneTilePool = blockModelGenerators.family(ChiseledBlocks.RED_SANDSTONE_TILES);
        redSandstoneTilePool.stairs(ChiseledBlocks.RED_SANDSTONE_TILE_STAIRS);
        redSandstoneTilePool.slab(ChiseledBlocks.RED_SANDSTONE_TILE_SLAB);
        redSandstoneTilePool.wall(ChiseledBlocks.RED_SANDSTONE_TILE_WALL);

        BlockModelGenerators.BlockFamilyProvider cutCinnabarBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_CINNABAR_BRICKS);
        cutCinnabarBrickPool.stairs(ChiseledBlocks.CUT_CINNABAR_BRICK_STAIRS);
        cutCinnabarBrickPool.slab(ChiseledBlocks.CUT_CINNABAR_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider cinnabarTilePool = blockModelGenerators.family(ChiseledBlocks.CINNABAR_TILES);
        cinnabarTilePool.stairs(ChiseledBlocks.CINNABAR_TILE_STAIRS);
        cinnabarTilePool.slab(ChiseledBlocks.CINNABAR_TILE_SLAB);
        cinnabarTilePool.wall(ChiseledBlocks.CINNABAR_TILE_WALL);

        BlockModelGenerators.BlockFamilyProvider cutSulfurBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_SULFUR_BRICKS);
        cutSulfurBrickPool.stairs(ChiseledBlocks.CUT_SULFUR_BRICK_STAIRS);
        cutSulfurBrickPool.slab(ChiseledBlocks.CUT_SULFUR_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider sulfurTilePool = blockModelGenerators.family(ChiseledBlocks.SULFUR_TILES);
        sulfurTilePool.stairs(ChiseledBlocks.SULFUR_TILE_STAIRS);
        sulfurTilePool.slab(ChiseledBlocks.SULFUR_TILE_SLAB);
        sulfurTilePool.wall(ChiseledBlocks.SULFUR_TILE_WALL);

        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.PRISMARINE_BRICK_WALL, Blocks.PRISMARINE_BRICKS, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider cutPrismarineBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_PRISMARINE_BRICKS);
        cutPrismarineBrickPool.stairs(ChiseledBlocks.CUT_PRISMARINE_BRICK_STAIRS);
        cutPrismarineBrickPool.slab(ChiseledBlocks.CUT_PRISMARINE_BRICK_SLAB);
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.DARK_PRISMARINE_WALL, Blocks.DARK_PRISMARINE, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider darkPrismarineBrickPool = blockModelGenerators.family(ChiseledBlocks.DARK_PRISMARINE_BRICKS);
        darkPrismarineBrickPool.stairs(ChiseledBlocks.DARK_PRISMARINE_BRICK_STAIRS);
        darkPrismarineBrickPool.slab(ChiseledBlocks.DARK_PRISMARINE_BRICK_SLAB);
        darkPrismarineBrickPool.wall(ChiseledBlocks.DARK_PRISMARINE_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutDarkPrismarineBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICKS);
        cutDarkPrismarineBrickPool.stairs(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICK_STAIRS);
        cutDarkPrismarineBrickPool.slab(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICK_SLAB);

        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.NETHERITE_STAIRS, Blocks.NETHERITE_BLOCK, blockModelGenerators);

        BlockModelGenerators.BlockFamilyProvider packedSnowBrickPool = blockModelGenerators.family(ChiseledBlocks.PACKED_SNOW_BRICKS);
        packedSnowBrickPool.stairs(ChiseledBlocks.PACKED_SNOW_BRICK_STAIRS);
        packedSnowBrickPool.slab(ChiseledBlocks.PACKED_SNOW_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider cutPackedSnowBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_PACKED_SNOW_BRICKS);
        cutPackedSnowBrickPool.stairs(ChiseledBlocks.CUT_PACKED_SNOW_BRICK_STAIRS);
        cutPackedSnowBrickPool.slab(ChiseledBlocks.CUT_PACKED_SNOW_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider packedSnowTilePool = blockModelGenerators.family(ChiseledBlocks.PACKED_SNOW_TILES);
        packedSnowTilePool.stairs(ChiseledBlocks.PACKED_SNOW_TILE_STAIRS);
        packedSnowTilePool.slab(ChiseledBlocks.PACKED_SNOW_TILE_SLAB);

        BlockModelGenerators.BlockFamilyProvider terracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.TERRACOTTA_BRICKS);
        terracottaBrickPool.stairs(ChiseledBlocks.TERRACOTTA_BRICK_STAIRS);
        terracottaBrickPool.slab(ChiseledBlocks.TERRACOTTA_BRICK_SLAB);
        terracottaBrickPool.wall(ChiseledBlocks.TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider whiteTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.WHITE_TERRACOTTA_BRICKS);
        whiteTerracottaBrickPool.stairs(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_STAIRS);
        whiteTerracottaBrickPool.slab(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_SLAB);
        whiteTerracottaBrickPool.wall(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider lightGrayTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICKS);
        lightGrayTerracottaBrickPool.stairs(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_STAIRS);
        lightGrayTerracottaBrickPool.slab(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_SLAB);
        lightGrayTerracottaBrickPool.wall(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider grayTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.GRAY_TERRACOTTA_BRICKS);
        grayTerracottaBrickPool.stairs(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_STAIRS);
        grayTerracottaBrickPool.slab(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_SLAB);
        grayTerracottaBrickPool.wall(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider blackTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.BLACK_TERRACOTTA_BRICKS);
        blackTerracottaBrickPool.stairs(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_STAIRS);
        blackTerracottaBrickPool.slab(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_SLAB);
        blackTerracottaBrickPool.wall(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider brownTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.BROWN_TERRACOTTA_BRICKS);
        brownTerracottaBrickPool.stairs(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_STAIRS);
        brownTerracottaBrickPool.slab(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_SLAB);
        brownTerracottaBrickPool.wall(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider redTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.RED_TERRACOTTA_BRICKS);
        redTerracottaBrickPool.stairs(ChiseledBlocks.RED_TERRACOTTA_BRICK_STAIRS);
        redTerracottaBrickPool.slab(ChiseledBlocks.RED_TERRACOTTA_BRICK_SLAB);
        redTerracottaBrickPool.wall(ChiseledBlocks.RED_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider orangeTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.ORANGE_TERRACOTTA_BRICKS);
        orangeTerracottaBrickPool.stairs(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_STAIRS);
        orangeTerracottaBrickPool.slab(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_SLAB);
        orangeTerracottaBrickPool.wall(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider yellowTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.YELLOW_TERRACOTTA_BRICKS);
        yellowTerracottaBrickPool.stairs(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_STAIRS);
        yellowTerracottaBrickPool.slab(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_SLAB);
        yellowTerracottaBrickPool.wall(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider limeTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.LIME_TERRACOTTA_BRICKS);
        limeTerracottaBrickPool.stairs(ChiseledBlocks.LIME_TERRACOTTA_BRICK_STAIRS);
        limeTerracottaBrickPool.slab(ChiseledBlocks.LIME_TERRACOTTA_BRICK_SLAB);
        limeTerracottaBrickPool.wall(ChiseledBlocks.LIME_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider greenTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.GREEN_TERRACOTTA_BRICKS);
        greenTerracottaBrickPool.stairs(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_STAIRS);
        greenTerracottaBrickPool.slab(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_SLAB);
        greenTerracottaBrickPool.wall(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cyanTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.CYAN_TERRACOTTA_BRICKS);
        cyanTerracottaBrickPool.stairs(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_STAIRS);
        cyanTerracottaBrickPool.slab(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_SLAB);
        cyanTerracottaBrickPool.wall(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider lightBlueTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICKS);
        lightBlueTerracottaBrickPool.stairs(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_STAIRS);
        lightBlueTerracottaBrickPool.slab(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_SLAB);
        lightBlueTerracottaBrickPool.wall(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider blueTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.BLUE_TERRACOTTA_BRICKS);
        blueTerracottaBrickPool.stairs(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_STAIRS);
        blueTerracottaBrickPool.slab(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_SLAB);
        blueTerracottaBrickPool.wall(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider purpleTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.PURPLE_TERRACOTTA_BRICKS);
        purpleTerracottaBrickPool.stairs(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_STAIRS);
        purpleTerracottaBrickPool.slab(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_SLAB);
        purpleTerracottaBrickPool.wall(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider magentaTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICKS);
        magentaTerracottaBrickPool.stairs(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_STAIRS);
        magentaTerracottaBrickPool.slab(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_SLAB);
        magentaTerracottaBrickPool.wall(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider pinkTerracottaBrickPool = blockModelGenerators.family(ChiseledBlocks.PINK_TERRACOTTA_BRICKS);
        pinkTerracottaBrickPool.stairs(ChiseledBlocks.PINK_TERRACOTTA_BRICK_STAIRS);
        pinkTerracottaBrickPool.slab(ChiseledBlocks.PINK_TERRACOTTA_BRICK_SLAB);
        pinkTerracottaBrickPool.wall(ChiseledBlocks.PINK_TERRACOTTA_BRICK_WALL);

        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_RED_NETHER_BRICKS);
        SilliestLibDataUtils.createStandaloneFence(ChiseledBlocks.RED_NETHER_BRICK_FENCE, Blocks.RED_NETHER_BRICKS, blockModelGenerators);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CHISELED_RED_NETHER_BRICKS);

        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.SMOOTH_BASALT_STAIRS, Blocks.SMOOTH_BASALT, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneSlab(ChiseledBlocks.SMOOTH_BASALT_SLAB, Blocks.SMOOTH_BASALT, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.SMOOTH_BASALT_WALL, Blocks.SMOOTH_BASALT, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider basaltBrickPool = blockModelGenerators.family(ChiseledBlocks.BASALT_BRICKS);
        basaltBrickPool.stairs(ChiseledBlocks.BASALT_BRICK_STAIRS);
        basaltBrickPool.slab(ChiseledBlocks.BASALT_BRICK_SLAB);
        basaltBrickPool.wall(ChiseledBlocks.BASALT_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cuBasaltBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_BASALT_BRICKS);
        cuBasaltBrickPool.stairs(ChiseledBlocks.CUT_BASALT_BRICK_STAIRS);
        cuBasaltBrickPool.slab(ChiseledBlocks.CUT_BASALT_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider basaltTilePool = blockModelGenerators.family(ChiseledBlocks.BASALT_TILES);
        basaltTilePool.stairs(ChiseledBlocks.BASALT_TILE_STAIRS);
        basaltTilePool.slab(ChiseledBlocks.BASALT_TILE_SLAB);
        basaltTilePool.wall(ChiseledBlocks.BASALT_TILE_WALL);

        BlockModelGenerators.BlockFamilyProvider cutPolishedBlackstoneBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_POLISHED_BLACKSTONE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_CUT_POLISHED_BLACKSTONE_BRICKS);
        cutPolishedBlackstoneBrickPool.stairs(ChiseledBlocks.CUT_POLISHED_BLACKSTONE_BRICK_STAIRS);
        cutPolishedBlackstoneBrickPool.slab(ChiseledBlocks.CUT_POLISHED_BLACKSTONE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider polishedBlackstoneTilePool = blockModelGenerators.family(ChiseledBlocks.POLISHED_BLACKSTONE_TILES);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_POLISHED_BLACKSTONE_TILES);
        polishedBlackstoneTilePool.stairs(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_STAIRS);
        polishedBlackstoneTilePool.slab(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_SLAB);
        polishedBlackstoneTilePool.wall(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_WALL);

        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.END_STONE_STAIRS, Blocks.END_STONE, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneSlab(ChiseledBlocks.END_STONE_SLAB, Blocks.END_STONE, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.END_STONE_WALL, Blocks.END_STONE, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider polishedEndStonePool = blockModelGenerators.family(ChiseledBlocks.POLISHED_END_STONE);
        polishedEndStonePool.stairs(ChiseledBlocks.POLISHED_END_STONE_STAIRS);
        polishedEndStonePool.slab(ChiseledBlocks.POLISHED_END_STONE_SLAB);
        polishedEndStonePool.wall(ChiseledBlocks.POLISHED_END_STONE_WALL);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_END_STONE_BRICKS);
        BlockModelGenerators.BlockFamilyProvider cutEndStoneBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_END_STONE_BRICKS);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_CUT_END_STONE_BRICKS);
        cutEndStoneBrickPool.stairs(ChiseledBlocks.CUT_END_STONE_BRICK_STAIRS);
        cutEndStoneBrickPool.slab(ChiseledBlocks.CUT_END_STONE_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider endStoneTilePool = blockModelGenerators.family(ChiseledBlocks.END_STONE_TILES);
        blockModelGenerators.createTrivialCube(ChiseledBlocks.CRACKED_END_STONE_TILES);
        endStoneTilePool.stairs(ChiseledBlocks.END_STONE_TILE_STAIRS);
        endStoneTilePool.slab(ChiseledBlocks.END_STONE_TILE_SLAB);
        endStoneTilePool.wall(ChiseledBlocks.END_STONE_TILE_WALL);

        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.QUARTZ_BRICK_STAIRS, Blocks.QUARTZ_BRICKS, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneSlab(ChiseledBlocks.QUARTZ_BRICK_SLAB, Blocks.QUARTZ_BRICKS, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.QUARTZ_BRICK_WALL, Blocks.QUARTZ_BRICKS, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider cutQuartzBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_QUARTZ_BRICKS);
        cutQuartzBrickPool.stairs(ChiseledBlocks.CUT_QUARTZ_BRICK_STAIRS);
        cutQuartzBrickPool.slab(ChiseledBlocks.CUT_QUARTZ_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider quartzTilePool = blockModelGenerators.family(ChiseledBlocks.QUARTZ_TILES);
        quartzTilePool.stairs(ChiseledBlocks.QUARTZ_TILE_STAIRS);
        quartzTilePool.slab(ChiseledBlocks.QUARTZ_TILE_SLAB);
        quartzTilePool.wall(ChiseledBlocks.QUARTZ_TILE_WALL);

        SilliestLibDataUtils.createStandaloneStairs(ChiseledBlocks.AMETHYST_STAIRS, Blocks.AMETHYST_BLOCK, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneSlab(ChiseledBlocks.AMETHYST_SLAB, Blocks.AMETHYST_BLOCK, blockModelGenerators);
        SilliestLibDataUtils.createStandaloneWall(ChiseledBlocks.AMETHYST_WALL, Blocks.AMETHYST_BLOCK, blockModelGenerators);
        BlockModelGenerators.BlockFamilyProvider amethystBrickPool = blockModelGenerators.family(ChiseledBlocks.AMETHYST_BRICKS);
        amethystBrickPool.stairs(ChiseledBlocks.AMETHYST_BRICK_STAIRS);
        amethystBrickPool.slab(ChiseledBlocks.AMETHYST_BRICK_SLAB);
        amethystBrickPool.wall(ChiseledBlocks.AMETHYST_BRICK_WALL);
        BlockModelGenerators.BlockFamilyProvider cutAmethystBrickPool = blockModelGenerators.family(ChiseledBlocks.CUT_AMETHYST_BRICKS);
        cutAmethystBrickPool.stairs(ChiseledBlocks.CUT_AMETHYST_BRICK_STAIRS);
        cutAmethystBrickPool.slab(ChiseledBlocks.CUT_AMETHYST_BRICK_SLAB);
        BlockModelGenerators.BlockFamilyProvider amethystTilePool = blockModelGenerators.family(ChiseledBlocks.AMETHYST_TILES);
        amethystTilePool.stairs(ChiseledBlocks.AMETHYST_TILE_STAIRS);
        amethystTilePool.slab(ChiseledBlocks.AMETHYST_TILE_SLAB);
        amethystTilePool.wall(ChiseledBlocks.AMETHYST_TILE_WALL);
    }

    @Override
    public void generateItemModels(ItemModelGenerators itemModelGenerators) {
    }
}