package net.hyper.chiseled.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.hyper.chiseled.registry.ChiseledBlocks;
import net.minecraft.core.HolderLookup;
import java.util.concurrent.CompletableFuture;

public class ChiseledLangGen extends FabricLanguageProvider {
    public ChiseledLangGen(FabricPackOutput dataOutput, CompletableFuture<HolderLookup.Provider> registryLookup) {
        super(dataOutput, registryLookup);
    }

    public void generateTranslations(HolderLookup.Provider registryLookup, TranslationBuilder translationBuilder) {
        translationBuilder.add(ChiseledBlocks.STONE_WALL, "Stone Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_STONE, "Polished Stone");
        translationBuilder.add(ChiseledBlocks.POLISHED_STONE_STAIRS, "Polished Stone Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_STONE_SLAB, "Polished Stone Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_STONE_WALL, "Polished Stone Wall");
        translationBuilder.add(ChiseledBlocks.SMOOTH_STONE_STAIRS, "Smooth Stone Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_STONE_BRICKS, "Cut Stone Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_STONE_BRICKS, "Cracked Cut Stone Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_STONE_BRICK_STAIRS, "Cut Stone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_STONE_BRICK_SLAB, "Cut Stone Brick Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_STONE_BRICKS, "Mossy Cut Stone Bricks");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_STONE_BRICK_STAIRS, "Mossy Cut Stone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_STONE_BRICK_SLAB, "Mossy Cut Stone Brick Slab");
        translationBuilder.add(ChiseledBlocks.STONE_TILES, "Stone Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_STONE_TILES, "Cracked Stone Tiles");
        translationBuilder.add(ChiseledBlocks.STONE_TILE_STAIRS, "Stone Tile Stairs");
        translationBuilder.add(ChiseledBlocks.STONE_TILE_SLAB, "Stone Tile Slab");
        translationBuilder.add(ChiseledBlocks.STONE_TILE_WALL, "Stone Tile Wall");
        translationBuilder.add(ChiseledBlocks.MOSSY_STONE_TILES, "Mossy Stone Tiles");
        translationBuilder.add(ChiseledBlocks.MOSSY_STONE_TILE_STAIRS, "Mossy Stone Tile Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_STONE_TILE_SLAB, "Mossy Stone Tile Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_STONE_TILE_WALL, "Mossy Stone Tile Wall");

        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_WALL, "Polished Granite Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_BRICKS, "Polished Granite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_GRANITE_BRICKS, "Cracked Polished Granite Bricks");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_BRICK_STAIRS, "Polished Granite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_BRICK_SLAB, "Polished Granite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_BRICK_WALL, "Polished Granite Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICKS, "Cut Polished Granite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_POLISHED_GRANITE_BRICKS, "Cracked Cut Polished Granite Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICK_STAIRS, "Cut Polished Granite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_GRANITE_BRICK_SLAB, "Cut Polished Granite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_TILES, "Polished Granite Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_GRANITE_TILES, "Cracked Polished Granite Tiles");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_TILE_STAIRS, "Polished Granite Tile Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_TILE_SLAB, "Polished Granite Tile Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_GRANITE_TILE_WALL, "Polished Granite Tile Wall");

        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_WALL, "Polished Diorite Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_BRICKS, "Polished Diorite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_DIORITE_BRICKS, "Cracked Polished Diorite Bricks");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_BRICK_STAIRS, "Polished Diorite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_BRICK_SLAB, "Polished Diorite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_BRICK_WALL, "Polished Diorite Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICKS, "Cut Polished Diorite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_POLISHED_DIORITE_BRICKS, "Cracked Cut Polished Diorite Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICK_STAIRS, "Cut Polished Diorite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_DIORITE_BRICK_SLAB, "Cut Polished Diorite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_TILES, "Polished Diorite Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_DIORITE_TILES, "Cracked Polished Diorite Tiles");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_TILE_STAIRS, "Polished Diorite Tile Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_TILE_SLAB, "Polished Diorite Tile Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_DIORITE_TILE_WALL, "Polished Diorite Tile Wall");

        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_WALL, "Polished Andesite Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_BRICKS, "Polished Andesite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_BRICKS, "Cracked Polished Andesite Bricks");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_STAIRS, "Polished Andesite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_SLAB, "Polished Andesite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_WALL, "Polished Andesite Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICKS, "Cut Polished Andesite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_POLISHED_ANDESITE_BRICKS, "Cracked Cut Polished Andesite Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICK_STAIRS, "Cut Polished Andesite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_POLISHED_ANDESITE_BRICK_SLAB, "Cut Polished Andesite Brick Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_TILES, "Polished Andesite Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_TILES, "Cracked Polished Andesite Tiles");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_TILE_STAIRS, "Polished Andesite Tile Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_TILE_SLAB, "Polished Andesite Tile Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_ANDESITE_TILE_WALL, "Polished Andesite Tile Wall");

        translationBuilder.add(ChiseledBlocks.CUT_DEEPSLATE_BRICKS, "Cut Deepslate Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_DEEPSLATE_BRICKS, "Cracked Cut Deepslate Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_DEEPSLATE_BRICK_STAIRS, "Cut Deepslate Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_DEEPSLATE_BRICK_SLAB, "Cut Deepslate Brick Slab");

        translationBuilder.add(ChiseledBlocks.CALCITE_STAIRS, "Calcite Stairs");
        translationBuilder.add(ChiseledBlocks.CALCITE_SLAB, "Calcite Slab");
        translationBuilder.add(ChiseledBlocks.CALCITE_WALL, "Calcite Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_CALCITE, "Polished Calcite");
        translationBuilder.add(ChiseledBlocks.POLISHED_CALCITE_STAIRS, "Polished Calcite Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_CALCITE_SLAB, "Polished Calcite Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_CALCITE_WALL, "Polished Calcite Wall");
        translationBuilder.add(ChiseledBlocks.CALCITE_BRICKS, "Calcite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CALCITE_BRICKS, "Cracked Calcite Bricks");
        translationBuilder.add(ChiseledBlocks.CALCITE_BRICK_STAIRS, "Calcite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CALCITE_BRICK_SLAB, "Calcite Brick Slab");
        translationBuilder.add(ChiseledBlocks.CALCITE_BRICK_WALL, "Calcite Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_CALCITE_BRICKS, "Cut Calcite Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_CALCITE_BRICKS, "Cracked Cut Calcite Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_CALCITE_BRICK_STAIRS, "Cut Calcite Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_CALCITE_BRICK_SLAB, "Cut Calcite Brick Slab");
        translationBuilder.add(ChiseledBlocks.CALCITE_TILES, "Calcite Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_CALCITE_TILES, "Cracked Calcite Tiles");
        translationBuilder.add(ChiseledBlocks.CALCITE_TILE_STAIRS, "Calcite Tile Stairs");
        translationBuilder.add(ChiseledBlocks.CALCITE_TILE_SLAB, "Calcite Tile Slab");
        translationBuilder.add(ChiseledBlocks.CALCITE_TILE_WALL, "Calcite Tile Wall");

        translationBuilder.add(ChiseledBlocks.DRIPSTONE_STAIRS, "Dripstone Stairs");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_SLAB, "Dripstone Slab");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_WALL, "Dripstone Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_DRIPSTONE, "Polished Dripstone");
        translationBuilder.add(ChiseledBlocks.POLISHED_DRIPSTONE_STAIRS, "Polished Dripstone Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_DRIPSTONE_SLAB, "Polished Dripstone Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_DRIPSTONE_WALL, "Polished Dripstone Wall");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_BRICKS, "Dripstone Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_DRIPSTONE_BRICKS, "Cracked Dripstone Bricks");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_BRICK_STAIRS, "Dripstone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_BRICK_SLAB, "Dripstone Brick Slab");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_BRICK_WALL, "Dripstone Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_DRIPSTONE_BRICKS, "Cut Dripstone Bricks");
        translationBuilder.add(ChiseledBlocks.CRACKED_CUT_DRIPSTONE_BRICKS, "Cracked Cut Dripstone Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_DRIPSTONE_BRICK_STAIRS, "Cut Dripstone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_DRIPSTONE_BRICK_SLAB, "Cut Dripstone Brick Slab");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_TILES, "Dripstone Tiles");
        translationBuilder.add(ChiseledBlocks.CRACKED_DRIPSTONE_TILES, "Cracked Dripstone Tiles");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_TILE_STAIRS, "Dripstone Tile Stairs");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_TILE_SLAB, "Dripstone Tile Slab");
        translationBuilder.add(ChiseledBlocks.DRIPSTONE_TILE_WALL, "Dripstone Tile Wall");

        translationBuilder.add(ChiseledBlocks.MIXED_BRICKS, "Mixed Bricks");
        translationBuilder.add(ChiseledBlocks.MIXED_BRICK_STAIRS, "Mixed Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MIXED_BRICK_SLAB, "Mixed Brick Slab");
        translationBuilder.add(ChiseledBlocks.MIXED_BRICK_WALL, "Mixed Brick Wall");
        translationBuilder.add(ChiseledBlocks.MOSSY_BRICKS, "Mossy Bricks");
        translationBuilder.add(ChiseledBlocks.MOSSY_BRICK_STAIRS, "Mossy Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_BRICK_SLAB, "Mossy Brick Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_BRICK_WALL, "Mossy Brick Wall");

        translationBuilder.add(ChiseledBlocks.PACKED_MUD_STAIRS, "Packed Mud Stairs");
        translationBuilder.add(ChiseledBlocks.PACKED_MUD_SLAB, "Packed Mud Slab");
        translationBuilder.add(ChiseledBlocks.PACKED_MUD_WALL, "Packed Mud Wall");
        translationBuilder.add(ChiseledBlocks.POLISHED_MUD, "Polished Mud");
        translationBuilder.add(ChiseledBlocks.POLISHED_MUD_STAIRS, "Polished Mud Stairs");
        translationBuilder.add(ChiseledBlocks.POLISHED_MUD_SLAB, "Polished Mud Slab");
        translationBuilder.add(ChiseledBlocks.POLISHED_MUD_WALL, "Polished Mud Wall");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_BRICKS, "Mossy Mud Bricks");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_BRICK_STAIRS, "Mossy Mud Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_BRICK_SLAB, "Mossy Mud Brick Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_BRICK_WALL, "Mossy Mud Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_MUD_BRICKS, "Cut Mud Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_MUD_BRICK_STAIRS, "Cut Mud Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_MUD_BRICK_SLAB, "Cut Mud Brick Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_MUD_BRICKS, "Mossy Cut Mud Bricks");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_MUD_BRICK_STAIRS, "Mossy Cut Mud Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_CUT_MUD_BRICK_SLAB, "Mossy Cut Mud Brick Slab");
        translationBuilder.add(ChiseledBlocks.MUD_TILES, "Mud Tiles");
        translationBuilder.add(ChiseledBlocks.MUD_TILE_STAIRS, "Mud Tile Stairs");
        translationBuilder.add(ChiseledBlocks.MUD_TILE_SLAB, "Mud Tile Slab");
        translationBuilder.add(ChiseledBlocks.MUD_TILE_WALL, "Mud Tile Wall");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_TILES, "Mossy Mud Tiles");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_TILE_STAIRS, "Mossy Mud Tile Stairs");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_TILE_SLAB, "Mossy Mud Tile Slab");
        translationBuilder.add(ChiseledBlocks.MOSSY_MUD_TILE_WALL, "Mossy Mud Tile Wall");

        translationBuilder.add(ChiseledBlocks.HONEYCOMB_STAIRS, "Honeycomb Stairs");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_SLAB, "Honeycomb Slab");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_WALL, "Honeycomb Wall");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_BRICKS, "Honeycomb Bricks");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_BRICK_STAIRS, "Honeycomb Brick Stairs");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_BRICK_SLAB, "Honeycomb Brick Slab");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_BRICK_WALL, "Honeycomb Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_HONEYCOMB_BRICKS, "Cut Honeycomb Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_HONEYCOMB_BRICK_STAIRS, "Cut Honeycomb Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_HONEYCOMB_BRICK_SLAB, "Cut Honeycomb Brick Slab");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_TILES, "Honeycomb Tiles");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_TILE_STAIRS, "Honeycomb Tile Stairs");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_TILE_SLAB, "Honeycomb Tile Slab");
        translationBuilder.add(ChiseledBlocks.HONEYCOMB_TILE_WALL, "Honeycomb Tile Wall");

        translationBuilder.add(ChiseledBlocks.SMOOTH_SANDSTONE_WALL, "Smooth Sandstone Wall");
        translationBuilder.add(ChiseledBlocks.SANDSTONE_BRICKS, "Sandstone Bricks");
        translationBuilder.add(ChiseledBlocks.SANDSTONE_BRICK_STAIRS, "Sandstone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.SANDSTONE_BRICK_SLAB, "Sandstone Brick Slab");
        translationBuilder.add(ChiseledBlocks.SANDSTONE_BRICK_WALL, "Sandstone Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_SANDSTONE_BRICKS, "Cut Sandstone Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_SANDSTONE_BRICK_STAIRS, "Cut Sandstone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_SANDSTONE_BRICK_SLAB, "Cut Sandstone Brick Slab");
        translationBuilder.add(ChiseledBlocks.SANDSTONE_TILES, "Sandstone Tiles");
        translationBuilder.add(ChiseledBlocks.SANDSTONE_TILE_STAIRS, "Sandstone Tile Stairs");
        translationBuilder.add(ChiseledBlocks.SANDSTONE_TILE_SLAB, "Sandstone Tile Slab");
        translationBuilder.add(ChiseledBlocks.SANDSTONE_TILE_WALL, "Sandstone Tile Wall");

        translationBuilder.add(ChiseledBlocks.SMOOTH_RED_SANDSTONE_WALL, "Smooth Red Sandstone Wall");
        translationBuilder.add(ChiseledBlocks.RED_SANDSTONE_BRICKS, "Red Sandstone Bricks");
        translationBuilder.add(ChiseledBlocks.RED_SANDSTONE_BRICK_STAIRS, "Red Sandstone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.RED_SANDSTONE_BRICK_SLAB, "Red Sandstone Brick Slab");
        translationBuilder.add(ChiseledBlocks.RED_SANDSTONE_BRICK_WALL, "Red Sandstone Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_RED_SANDSTONE_BRICKS, "Cut Red Sandstone Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_RED_SANDSTONE_BRICK_STAIRS, "Cut Red Sandstone Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_RED_SANDSTONE_BRICK_SLAB, "Cut Red Sandstone Brick Slab");
        translationBuilder.add(ChiseledBlocks.RED_SANDSTONE_TILES, "Red Sandstone Tiles");
        translationBuilder.add(ChiseledBlocks.RED_SANDSTONE_TILE_STAIRS, "Red Sandstone Tile Stairs");
        translationBuilder.add(ChiseledBlocks.RED_SANDSTONE_TILE_SLAB, "Red Sandstone Tile Slab");
        translationBuilder.add(ChiseledBlocks.RED_SANDSTONE_TILE_WALL, "Red Sandstone Tile Wall");

        translationBuilder.add(ChiseledBlocks.PRISMARINE_BRICK_WALL, "Prismarine Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_PRISMARINE_BRICKS, "Cut Prismarine Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_PRISMARINE_BRICK_STAIRS, "Cut Prismarine Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_PRISMARINE_BRICK_SLAB, "Cut Prismarine Brick Slab");
        translationBuilder.add(ChiseledBlocks.DARK_PRISMARINE_WALL, "Dark Prismarine Wall");
        translationBuilder.add(ChiseledBlocks.DARK_PRISMARINE_BRICKS, "Dark Prismarine Bricks");
        translationBuilder.add(ChiseledBlocks.DARK_PRISMARINE_BRICK_STAIRS, "Dark Prismarine Brick Stairs");
        translationBuilder.add(ChiseledBlocks.DARK_PRISMARINE_BRICK_SLAB, "Dark Prismarine Brick Slab");
        translationBuilder.add(ChiseledBlocks.DARK_PRISMARINE_BRICK_WALL, "Dark Prismarine Brick Wall");
        translationBuilder.add(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICKS, "Cut Dark Prismarine Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICK_STAIRS, "Cut Dark Prismarine Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_DARK_PRISMARINE_BRICK_SLAB, "Cut Dark Prismarine Brick Slab");

        translationBuilder.add(ChiseledBlocks.PACKED_SNOW_BRICKS, "Packed Snow Bricks");
        translationBuilder.add(ChiseledBlocks.PACKED_SNOW_BRICK_STAIRS, "Packed Snow Brick Stairs");
        translationBuilder.add(ChiseledBlocks.PACKED_SNOW_BRICK_SLAB, "Packed Snow Brick Slab");
        translationBuilder.add(ChiseledBlocks.CUT_PACKED_SNOW_BRICKS, "Cut Packed Snow Bricks");
        translationBuilder.add(ChiseledBlocks.CUT_PACKED_SNOW_BRICK_STAIRS, "Cut Packed Snow Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CUT_PACKED_SNOW_BRICK_SLAB, "Cut Packed Snow Brick Slab");
        translationBuilder.add(ChiseledBlocks.PACKED_SNOW_TILES, "Packed Snow Tiles");
        translationBuilder.add(ChiseledBlocks.PACKED_SNOW_TILE_STAIRS, "Packed Snow Tile Stairs");
        translationBuilder.add(ChiseledBlocks.PACKED_SNOW_TILE_SLAB, "Packed Snow Tile Slab");

        translationBuilder.add(ChiseledBlocks.TERRACOTTA_BRICKS, "Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.TERRACOTTA_BRICK_STAIRS, "Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.TERRACOTTA_BRICK_SLAB, "Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.TERRACOTTA_BRICK_WALL, "Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.WHITE_TERRACOTTA_BRICKS, "White Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_STAIRS, "White Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_SLAB, "White Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.WHITE_TERRACOTTA_BRICK_WALL, "White Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICKS, "Light Gray Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_STAIRS, "Light Gray Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_SLAB, "Light Gray Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_BRICK_WALL, "Light Gray Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.GRAY_TERRACOTTA_BRICKS, "Gray Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_STAIRS, "Gray Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_SLAB, "Gray Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.GRAY_TERRACOTTA_BRICK_WALL, "Gray Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.BLACK_TERRACOTTA_BRICKS, "Black Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_STAIRS, "Black Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_SLAB, "Black Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.BLACK_TERRACOTTA_BRICK_WALL, "Black Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.BROWN_TERRACOTTA_BRICKS, "Brown Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_STAIRS, "Brown Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_SLAB, "Brown Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.BROWN_TERRACOTTA_BRICK_WALL, "Brown Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.RED_TERRACOTTA_BRICKS, "Red Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.RED_TERRACOTTA_BRICK_STAIRS, "Red Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.RED_TERRACOTTA_BRICK_SLAB, "Red Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.RED_TERRACOTTA_BRICK_WALL, "Red Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.ORANGE_TERRACOTTA_BRICKS, "Orange Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_STAIRS, "Orange Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_SLAB, "Orange Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.ORANGE_TERRACOTTA_BRICK_WALL, "Orange Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.YELLOW_TERRACOTTA_BRICKS, "Yellow Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_STAIRS, "Yellow Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_SLAB, "Yellow Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.YELLOW_TERRACOTTA_BRICK_WALL, "Yellow Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.LIME_TERRACOTTA_BRICKS, "Lime Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.LIME_TERRACOTTA_BRICK_STAIRS, "Lime Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.LIME_TERRACOTTA_BRICK_SLAB, "Lime Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.LIME_TERRACOTTA_BRICK_WALL, "Lime Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.GREEN_TERRACOTTA_BRICKS, "Green Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_STAIRS, "Green Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_SLAB, "Green Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.GREEN_TERRACOTTA_BRICK_WALL, "Green Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.CYAN_TERRACOTTA_BRICKS, "Cyan Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_STAIRS, "Cyan Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_SLAB, "Cyan Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.CYAN_TERRACOTTA_BRICK_WALL, "Cyan Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICKS, "Light Blue Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_STAIRS, "Light Blue Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_SLAB, "Light Blue Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_BRICK_WALL, "Light Blue Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.BLUE_TERRACOTTA_BRICKS, "Blue Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_STAIRS, "Blue Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_SLAB, "Blue Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.BLUE_TERRACOTTA_BRICK_WALL, "Blue Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.PURPLE_TERRACOTTA_BRICKS, "Purple Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_STAIRS, "Purple Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_SLAB, "Purple Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.PURPLE_TERRACOTTA_BRICK_WALL, "Purple Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICKS, "Magenta Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_STAIRS, "Magenta Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_SLAB, "Magenta Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.MAGENTA_TERRACOTTA_BRICK_WALL, "Magenta Terracotta Brick Wall");
        translationBuilder.add(ChiseledBlocks.PINK_TERRACOTTA_BRICKS, "Pink Terracotta Bricks");
        translationBuilder.add(ChiseledBlocks.PINK_TERRACOTTA_BRICK_STAIRS, "Pink Terracotta Brick Stairs");
        translationBuilder.add(ChiseledBlocks.PINK_TERRACOTTA_BRICK_SLAB, "Pink Terracotta Brick Slab");
        translationBuilder.add(ChiseledBlocks.PINK_TERRACOTTA_BRICK_WALL, "Pink Terracotta Brick Wall");

        translationBuilder.add(ChiseledBlocks.NETHERITE_STAIRS, "Netherite Stairs");

        translationBuilder.add("advancements.chiseled.swaggiest_stairs_ever.title", "Swaggiest Stairs Ever");
        translationBuilder.add("advancements.chiseled.swaggiest_stairs_ever.description", "Craft Netherite Stairs");

        translationBuilder.add("itemgroup.chiseled.chiseled", "Chiseled");
        translationBuilder.add("text.chiseled.data_overrides", "Data Overrides");
    }
}